services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATABASE: ${DB_DATABASE}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - pg-data:/var/lib/prostgresql/data
    restart: always

volumes:
  pg-data: